version: "3.9"
services:
  db:
    build: ./db
    networks:
      - redlock-network
  php-webserver:
    build: ./php
    networks:
      - redlock-network
    ports:
      - 8000:80
    depends_on: 
      - db

networks:
  redlock-network:
    ipam:
      driver: bridge
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254