version: "3.9"
services:
  db:
    build: ./db
    networks:
      - redlock-network  
  redlock-web-2.0:
    build: ./php
    networks:
      - redlock-network
    ports:
      - 7077:80
    depends_on: 
      - db

networks:
  redlock-network:
