FROM mysql


COPY ./redlock.sql .

ENV MYSQL_ROOT_PASSWORD=
ENV MYSQL_DATABASE=redlock
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password



# CMD  yes '' | mysql -u root -p redlock < ./redlock.sql
# CMD  tail -f /dev/null
COPY ./mysql /var/lib/mysql
