FROM mysql

COPY ./mysqld.cnf /etc/mysql/conf.d/my.cnf
COPY ./my.cnf /etc/my.cnf

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=redlock
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

COPY ./redlock.sql /docker-entrypoint-initdb.d/init.sql