FROM php:8.1-apache
COPY ./app/ /app
WORKDIR /app
COPY /app/ /var/www/html/
RUN chmod -R 774 /var/www/html

RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
  systemctl

RUN systemctl enable apache2 && systemctl start apache2
CMD ["apache2-foreground"]